# Generated by Django 2.2.6 on 2019-10-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0002_auto_20191026_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
