# Generated by Django 2.2.6 on 2019-10-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.IntegerField()),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('batch', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password1', models.CharField(max_length=50)),
                ('Password2', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
